site_name: pipe21
site_url: https://tandav.github.io/pipe21
repo_url: https://github.com/tandav/pipe21
repo_name: tandav/pipe21
edit_uri: edit/master/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/logo.png
  features:
    - navigation.instant
    - content.action.edit
    - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
