name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: install wheel
        run: python3 -m pip install wheel

      - name: install dependencies
        run: python3 -m pip install .[dev]

      - name: test
        run: make test

      # - name: mypy
      #   run: make mypy


  build-and-publish-to-pypi:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags')"
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pypa/build
        run: python -m pip install --upgrade build

      - name: Build a source tarball and wheel
        run: python -m build .

      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #    repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
